print("List Music: \n")
print(
    "1. 4U\n"
    "2. C U Again\n"
    "3. Dreams\n"
    "4. Everything\n"
    "5. Fearless\n"
    "6. Fight Back\n"
    "7. Get Busy\n"
    "8. Grateful\n"
    "9. Happier\n"
    "10. Heroes Tonight\n"
    "11. Inspiration\n"
    "12. Light It Up\n"
    "13. Linked\n"
    "14. Make Me Move\n"
    "15. Melody\n"
    "16. Perfect 10\n"
    "17. Pokemon\n"
    "18. Rise\n"
    "19. Sandy Freaks\n"
    "20. Savannah\n"
    "21. Season\n"
    "22. Shootin Stars\n"
    "23. Stronger\n"
    "24. Sunflower\n"
    "25. Sweet Scar\n"
    "26. The Next Episode\n"
    "27. Top 20 songs of NEFFEX 2018\n"
    "28. Traffic Light\n"
    "29. Vacation\n"
    "30. Weakness\n"
    "31. Why We Lose\n"
    "32. Wicked Ways\n"
    "33. With You\n"
)